[package]
name = "DevTrailsGUC"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
minijinja = "2"
tower-http = { version = "0.5", features = ["fs"] }
